### ISSUE TITLE
Cannot open Echo message box or notification page

### ISSUE THREAD

**Issue by olsonjaredm** [CanastaWiki/Canasta#101]
On Canasta versions 1.0.1 and 1.1.0 using the Chameleon skin and stock Echo version, the bell and message box icons at the top do not respond when clicked. If you go to `Special:Notifications`, the page loads but the message box hangs with a loading symbol.

On 1.0.1 I resolved the issue by updating to version `2916ed0` of the Echo extension for MediaWiki REL1_35. Previously Version showed `-` and now it shows `- (2916ed0) 23:24, 15 May 2022` and buttons and Notif page are functional. I have not tested `2916ed0` on 1.1.0.

**Comment by tosfos** [comment]
Looks to be fixed
