### ISSUE TITLE
`$wgServer` should be set with `.env` value in CanastaDefaultSettings.php

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#104]
`$wgServer` can currently be set to a value that is different from what is set in `.env`. To allow for consistency, let's set this value in CanastaDefaultSettings.php. In case that convention upsets anybody, this value can be overridden by the sysadmin in their `LocalSettings.php` anyway.

**Comment by vedmaka** [comment]
Closed by https://github.com/CanastaWiki/Canasta/pull/105
