### ISSUE TITLE
Remove SocialProfile extension?

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#107]
The SocialProfile extension adds various social media-related features to a wiki, like avatars, friending, etc.:

https://www.mediawiki.org/wiki/Extension:SocialProfile

It's part of Canasta, though I was surprised to discover today that it still lacks an extension.json file, which of course means that cfLoadExtension() won't work on it:

https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/SocialProfile/+/refs/heads/master

As we've discussed about other extensions, we can either try to fix this extension up (presumably, adding an extension.json file would be enough) or remove it.

(I was worried, by the way, that SocialProfile not working means that the other SocialProfile-related extensions in Canasta (AJAXPoll, VoteNY, WikiForum) don't work either, but it looks like none of these are dependent on SocialProfile - they're just all in the same "family". And these all do have an extension.json file.)

I'm not sure which way I go on this, in part because I don't know how popular an extension SocialProfile is. It certainly seems useful, and well-established, but I'm not sure I know of any specific wikis that use it. I don't believe it's included in any other MediaWiki distributions or farms, for what it's worth - except for ShoutWiki, where it was developed, but my understanding is that ShoutWiki is kind of neglected at the moment. Perhaps the lack of an extension.json file indicates some bigger issue - I don't know.

Any thoughts?

**Comment by jeffw16** [comment]
Ooh... this is a tough one.

We have some wikis on MyWikis who use this. I would say that these wikis would cancel their service with us if they couldn't use this extension. I'm inclined to say that this extension is important enough that it checks off the popularity requirement.

However, the codebase is a different story. We have identified that it uses ancient code for its avatar and award image upload system (dating back to MediaWiki 1.10!) and it's apparently very messy to fix. Nobody has gotten around to it. My colleague contacted Jack Phoenix, who says it's a hairy issue to fix and they wouldn't be fixing it anytime soon.

I would hate to see this extension be removed, but its poor development support is cause for serious concern. I would vote for removal if a third person (someone other than Yaron and me) agrees.

**Comment by yaronkoren** [comment]
That's good to know. Let me note that SocialProfile seems like an ideal example of the potential usefulness of a "Canasta Foundation" - a foundation that would pool resources to ensure that the necessary extensions and other utilities are maintained. SocialProfile has the right combination of being essential for some people and being poorly maintained. That doesn't really affect the current decision, though.

**Comment by tosfos** [comment]
I think we should keep it. And I guess users can figure out how to include it using require_once(). My reasoning is that even though the code is outdated, it does mostly work, it's useful and it's a [popular extension](https://wikiapiary.com/wiki/Extension:SocialProfile).

There is a [Phab task](https://phabricator.wikimedia.org/T152865) for extension registration, with a [patch](https://gerrit.wikimedia.org/r/c/mediawiki/extensions/SocialProfile/+/657651/) waiting for merge.

To sweeten the deal :), if it stops being maintained WikiTeq will likely pick it up. That doesn't mean we'd improve the code or fix all of the bugs, but it means they won't get worse.

**Comment by yaronkoren** [comment]
@tosfos - thanks for the response. Your first link is to WikiApiary, and that site usually times out for me but I was at one point able to view the page. SocialProfile is in use on around 200 wikis - which is maybe not hugely popular, but popular enough.

That Phabricator task you linked to is from December 2016, and the patch is from January 2021. So if the goal is to show that this task is in progress, you might have had the opposite effect. :) It seems like this is either a complex, hard-to-modify extension, or the people in charge of it are not that interested in maintaining it, or both. But basically, if you're willing to (and can) take over this extension, it seems like now would already be the time to do it...

**Comment by tosfos** [comment]
I think for this particular patch, it's "both". But I'm not sure the extension is unmaintained right now. There is some action on commits. There are shortcomings, but as far as MediaWiki extensions go, it's not bad.

**Comment by jeffw16** [comment]
SocialProfile is still being maintained, but it is not undergoing active development/reworks, if that makes any sense.

**Comment by yaronkoren** [comment]
@jeffw16 - I think you mean that the usual gang of maintainers are making sure that the extension stays up to date with MediaWiki, like they do with all extensions (they definitely do with mine, thankfully!), but that, beyond that, there's no attempt to improve the functionality.

So, now we have an extension with no extension.json file, because its authors lack the time and/or interest in adding it. This is both a problem on its own, and (in my opinion) a red flag about any future issues that could come up with the extension. That's why I say that, if there's a possibility of taking over this extension, the time for that has already come.

**Comment by tosfos** [comment]
WikiTeq has its hands full with extension maintenance right now, especially with 1.39 around the corner. If the extension authors believe they're maintaining it, we're inclined to agree. Even if WikiTeq did pick up maintenance, I don't think we'd prioritize code improvement and resolving any bugs unless they're critical.

**Comment by yaronkoren** [comment]
I can certainly understand a lack of development time. And maybe there is some maintenance going on; I don't know. All I know is that SocialProfile still lacks an extension.json file, and doesn't seem on track toward getting it. Given that, I think there's a strong case for removing SocialProfile from Canasta, and keeping it out until it has an extension.json file. As I said before, the lack of that file is both a problem in itself, and a flag that there may be other issues as well.

**Comment by tosfos** [comment]
I don't have any objection to this, and we have experienced unusual bugs with the extension. On the other hand, the fact that we did originally include it and it is important where installed makes removing it not so consistent with our stability philosophy. @jeffw16 ?

**Comment by jeffw16** [comment]
I don't think it should be removed, but only because it is so important, not because it has good code or good maintenance. Maybe we can add a warning to it.

**Comment by yaronkoren** [comment]
Well, MediaWiki 1.39 was released recently, which means that it's time to start getting ready to release our own new version of Canasta. SocialProfile still lacks an extension.json file, and doesn't seem any closer to getting it. One other interesting thing I discovered recently is that Canasta contains two large patches to SocialProfile:

https://github.com/CanastaWiki/Canasta/blob/master/_sources/patches/social-profile-REL1_35.44b4f89.diff
https://github.com/CanastaWiki/Canasta/blob/master/_sources/patches/SocialProfile-disable-fields.patch

The first one is just a security fix that was added to SocialProfile in 2021:

https://phabricator.wikimedia.org/rESPR58d2420c0f726cd469c638043ed66a4374b136f2

The second one, though, appears to be an entirely original patch to SocialProfile, created by @vedmaka for WikiTeq, that makes some pretty substantial changes to SocialProfile: it adds a new special page, Special:ManageFields; adds a new database table; and makes some other changes. So this patch would possibly have to be recreated, with the latest SocialProfile version - I don't know.

@tosfos - now I'm curious as to why you were so willing to get rid of this extension, given that WikiTeq created a patched, almost forked, version of it. Or do you no longer need this particular set of features? Or do you still need this alternate version, but now it can be placed "downstream" of Canasta?

**Comment by tosfos** [comment]
We still need it, but we don't need it to be part of Canasta itself.

We really should try to get those patches merged, or at least put them into code review. Pinging @alexey.

**Comment by yaronkoren** [comment]
Since there has been some sentiment in favor of keeping this extension (especially from @jeffw16), I think the best course of action for now is to keep this extension - with a warning on the website that wfLoadExtension() can't be used for SocialProfile, you have to use the old syntax. The patches for it should be removed, but that's really a separate issue. So, I'm closing this task.
