### ISSUE TITLE
Set $wgDisableCounters = false to prevent SESP 2.1.0 error

### ISSUE THREAD

**Issue by olsonjaredm** [CanastaWiki/Canasta#111]
### Setup and configuration
SMW version: 3.2.3
SESP version: 2.1.0
MW version: 1.35.6

On Canasta 1.1.0, in the logs (and on pages if `ini_set( 'display_errors', 1 );`) I get:
`Undefined index: wgDisableCounters in /var/www/html/extensions/SemanticExtraSpecialProperties/SemanticExtraSpecialProperties.php on line 124`

This link documents the exact issue, resolved by adding `$wgDisableCounters = false;` to LocalSettings.php:
https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/147

A bug fix is included in SESP 3.0.1 (2022-01-26).

**Comment by olsonjaredm** [comment]
https://www.mediawiki.org/wiki/Manual:$wgDisableCounters

https://www.mediawiki.org/wiki/Extension:Semantic_Extra_Special_Properties

**Comment by jeffw16** [comment]
Does this mean we can simply resolve this issue by upgrading SESP to 3.0.1? If so, for 1.1.1, should we just upgrade SESP to 3.0.1 then? I suppose we can issue a patch fix for 1.1.0 by setting `$wgDisableCounters` to `false` since it won't affect the rest of MediaWiki.

**Comment by olsonjaredm** [comment]
Yes, both make sense to me; patch fix to 1.1.0 and full upgrade to 3.0.1 for 1.1.1.
Here's link to the 3.0.1 fix: https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/commit/a76a11fc7c73e3dcdc3fc22e2563203249795b63

**Comment by yaronkoren** [comment]
It no longer makes sense to do this, I think, now that Canasta 1.3 is released, which includes version 3.0.1 of SESP.
