### ISSUE TITLE
Add CookieWarning extension

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#120]
I think we should add the CookieWarning extension to Canasta:

https://www.mediawiki.org/wiki/Extension:CookieWarning

It adds one of those now-ubiquitous "This site uses cookies. Is that OK?" dialogs to the wiki. It's a widely-used extension, seems to work well, and (to the extent that I understand the law) offers functionality needed by anyone running a public Canasta-based site in the EU.

**Comment by tosfos** [comment]
I'd rather change the law. But if that's not an option, we should add this extension.

**Comment by jeffw16** [comment]
I also think we should add it.

**Comment by yaronkoren** [comment]
I agree that it would be better to get rid of GDPR, but until we can do that, I'm glad you both agree that this is the next best thing! I just created a patch for it.
