### ISSUE TITLE
Hardcoded docker host address

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#126]
There is a need for container to connect to Docker host for:

1. Sending emails
2. Do VisualEditor Parsoid API calls

Right now there is a hard-coded default `172.17.0.1` [[1]](https://github.com/CanastaWiki/Canasta/blob/master/_sources/configs/msmtprc#L9) [[2]](https://github.com/CanastaWiki/Canasta/blob/master/_sources/scripts/run-apache.sh#L65) address for Docker host being used, this works fine most of the time, however, considering default bridge network may vary either due to changes made to Docker `daemon.json` configuration file on target host or due to hitting limit of subnets occupied.

It'd be better to have this address detected automatically, fortunately, starting Docker `20.04` this is possible via `--add-host=host.docker.internal:host-gateway` param or `extra_hosts` attribute in a Compose file

**Comment by yaronkoren** [comment]
Closing, given that this seems to have been fixed in August.
