### ISSUE TITLE
Add skip-binary-as-hex setting for mysql

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#128]
We had an issue with the mysql command-line client displaying all data as hexadecimal values in one Canasta-based wiki. We solved it by adding the following to the file /etc/my.cnf:

> [client]
> skip-binary-as-hex = true
> 
> [mysql]
> skip-binary-as-hex = true

It would be great to add this setting by default within Canasta in some way, if that's possible, so that this kind of problem doesn't happen again for administrators.

**Comment by jeffw16** [comment]
Is this a Canasta thing or a MySQL Docker image thing?

**Comment by yaronkoren** [comment]
Well, I suppose the latter, but there's no way for us to modify the MySQL image, is there? But however this can be done would be good.

**Comment by jeffw16** [comment]
Such a change should be done on https://github.com/CanastaWiki/Canasta-DockerCompose I think.

**Comment by yaronkoren** [comment]
Okay, I posted this same issue there:

https://github.com/CanastaWiki/Canasta-DockerCompose/issues/19

Should I just close this one?

**Comment by yaronkoren** [comment]
Closing issue - this was fixed in Docker Compose.
