### ISSUE TITLE
Remove Contribution Scores extension

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#132]
The Contribution Scores extension has been in Canasta since the beginning, and it seems to be working fine:

https://www.mediawiki.org/wiki/Extension:Contribution_Scores

There's one problem with it, though: it lacks a license. And the extension's main author, Tim Laqua, has apparently not been heard from since 2013 or so, and recent attempts to contact him have failed. So we have no way of knowing for sure that he intended this extension to be open source.

According to Kunal Mehta, that makes it "legally precarious" for anyone to use the extension:

https://phabricator.wikimedia.org/T187483

So, the plan is to archive the extension next year, unless Tim can be found.

Kunal recommends doing a "clean room re-implementation" - i.e., getting someone who hasn't looked at the Contribution Scores code to create a new extension that matches the functionality. Having looked at the CS code (sorry, that means it can't be me!), it doesn't look too bad - it's basically just one PHP file, which creates one table. But, regardless, it seems like we probably need to get rid of Contribution Scores.

**Comment by WolfgangFahl** [comment]
@yaronkoren - just sent a message to https://www.linkedin.com/in/timlaqua/ to look into this - i assume the linkedin profile is his given that https://www.mediawiki.org/wiki/User:Tim_Laqua points to the same university as the linkedin profile

**Comment by tlaqua** [comment]
Yes, it's intended to be open source.

**Comment by yaronkoren** [comment]
@tlaqua - wow, it's great to hear from you! Thanks for responding. (And thank you @WolfgangFahl for handling the communication.) Also, thank you for making this extension open source. :) I don't know if this single sentence is enough, legally speaking, because I don't know if there's any proof that this GitHub account is the real you. If it's possible, could you add a comment to the Phabricator page linked above, or modify the mediawiki.org page directly - in either case with your user account - to specify what license you want this extension to have? If you've lost access to both these accounts, I guess we'll have to think of some other option.

**Comment by tlaqua** [comment]
I don't even know what licenses are common these days, but if you ask a question in the discussion page about it, I can confirm whatever license you want.

**Comment by yaronkoren** [comment]
@tlaqua - okay; in that case, could you just edit the main mediawiki.org page for Contribution Scores, find the line with `license=`, and add `GPL-2.0-or-later` to it? That's the license most extensions use, I think. (Though if you really prefer using the talk page, we can do that too.)

**Comment by tlaqua** [comment]
Updated

**Comment by yaronkoren** [comment]
@tlaqua - thank you! One small edit, but it has made a lot of people's lives easier. :) Excelsior!

I think we can close this task now...
