### ISSUE TITLE
Upgrade from EOL ElasticSearch 6 to OpenSearch

### ISSUE THREAD

**Issue by tuxayo** [CanastaWiki/Canasta#138]
OpenSearch (1.x or 2.x) is the only supported ElasticSearch implementation that is still libre/open source. The license change starting with version 7.11 isn't considered libre/open source by Debian, Fedora and the OSI.

https://en.wikipedia.org/wiki/OpenSearch_(software)

https://endoflife.date/opensearch
> All future OpenSearch 1.x releases will be backwards compatible with Elasticsearch 7.10.

The easiest would be to upgrade to OS 1.x since it should be the same as upgrading to ES 7.

**Comment by tuxayo** [comment]
Wait, this depends on MediaWiki/cirrussearch support.

https://www.mediawiki.org/wiki/Extension:CirrusSearch

> MediaWiki 1.33.x - 1.38.x require Elasticsearch 6.5.x - 6.8.x. (6.8.23+ recommended)
> MediaWiki 1.39+ require Elasticsearch 7.10.2 (6.8.23+ is possible using a [compatibility layer](https://www.mediawiki.org/wiki/Special:MyLanguage/Extension:CirrusSearch/ES6CompatTransportWrapper))

Ok so this needs to find or open a ticket to try to convince (if a security issue like the Log4J ones happens it will be bad) backporting the support of ES7 or OpenSearch to MediaWiki 1.35 LTS, is that correct?
Where should such ticket be? On cirrussearch?
https://phabricator.wikimedia.org/tag/cirrussearch/
https://phabricator.wikimedia.org/maniphest/task/edit/form/1/?projects=cirrussearch

**Comment by jeffw16** [comment]
You can open a Phabricator ticket but I believe this is currently on the table with the Search team.

This is out of the scope of Canasta and currently not supported by the WMF. Closing this issue.

**Comment by jeffw16** [comment]
I just want to note that just because Canasta is open source doesn’t mean we are able to choose every single dependency as the open source version. Zend Engine isn't considered copyleft but we have no choice but to use it for MediaWiki. Also, lastly, OpenSearch is essentially made by Amazon, who isn't exactly known for being "earth's best employer."

**Comment by tuxayo** [comment]
> I just want to note that just because Canasta is open source doesn’t mean we are able to choose every single dependency as the open source version.

Of course, upstream has a major influence. It was never about having a fork of MediaWiki to support it.

**Comment by tuxayo** [comment]
> Zend Engine isn't considered copyleft but we have no choice but to use it for MediaWiki

It's not about copyleft, it's just about being libre/open source. We are not at a point to have everything copyleft to prevent non libre forks unfortunately :(
Though there is indeed something fishy about the Zend Engine License. At least the FSF accepted it and Debian half accepted it. https://en.wikipedia.org/wiki/Zend_Engine_License

> Also, lastly, OpenSearch is essentially made by Amazon, who isn't exactly known for being "earth's best employer."

Yes, Amazon can burn as a group. Even for specific stuff about AWS, they are in an oligopoly position and are not enough contributing to the projects they make a fortune hosting. So screw them. 
Though the functional alternative is ElasticSearch which the consensus leans towards being not libre anymore. Using a non-libre dependency from a publicly traded company that closed the license after the software became popular is a huge no.

Best is to be in a position of not needing an advanced search engine like ElasticSearch. It's a shame, it was good.

**Comment by tuxayo** [comment]
Related question: since MediaWiki doesn't depend on ES, is it possible to disable it on Canasta? In addition of the above reasons, it's also for RAM usage for small wikis that don't need such search capabilities.
And directly related to this ticket: to remove a security risk.

**Comment by jeffw16** [comment]
Yes, you can disable it on your Docker Compose stack by modifying the `docker-compose{.override}.yml` file.

**Comment by tuxayo** [comment]
Thanks a lot! :)

**Comment by tuxayo** [comment]
> You can open a Phabricator ticket but I believe this is currently on the table with the Search team.

I didn't found something that seems related in the workboard of CirrusSearch. Here is a ticket: https://phabricator.wikimedia.org/T325028

About something earlier:

> This is out of the scope of Canasta and currently not supported by the WMF. Closing this issue.

It would be valid (and a good political goal) to aim when possible to have libre dependencies. So it could be on scope to open tickets upstream and track them here. So crossing fingers to have things moving upstream. Now that 1.39 LTS was released, ES 7 support is here and OS 1.x hopefully won't cause much trouble.

**Comment by yaronkoren** [comment]
Hi @tuxayo - speaking as a Canasta developer, I definitely support having the software stack be fully open-source. We of course have to balance the competing interests, and in the case of Elasticsearch, I don't think we really have a choice at the moment but to go with it.

**Comment by FelipoAntonoff** [comment]
There's also this very interesting Opensource search engine https://github.com/meilisearch/meilisearch, but I don't know if it has native support for Mediawiki, who knows maybe in the future, there's even an sdk for PHP https://www.meilisearch .com/docs/learn/what_is_meilisearch/sdks#sdks
