### ISSUE TITLE
Add custom startup code running point in `run_apache.sh`

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#140]
Canasta derivatives can have valid reasons to run code at runtime rather than compile time (i.e. when the Docker image is compiled). For instance, if they want to make database updates, it needs to be done at runtime because there is no database available at compile time. In these cases, we should add a point (or multiple points) in `run_apache.sh` for them to run their scripts.

**Comment by yaronkoren** [comment]
I believe #228 would take care of this, if I understand the request correctly...

**Comment by yaronkoren** [comment]
Done with the maintenance-scripts/ directory addition, I believe.
