### ISSUE TITLE
Remove "Semantic MediaWiki was installed but not enabled on this wiki" message from Special:Version

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#143]
Semantic MediaWiki displays the following "error message" at the top of Special:Version if it's installed but not enabled:

> Semantic MediaWiki was installed but not enabled on this wiki. Please consult the [help page](https://www.semantic-mediawiki.org/wiki/Extension_registration) for instructions and further assistances [sic].

Regardless of whether or not this error message is ever a good idea, it's bad in Canasta - where, due (I think) to the way the Validator extension gets installed via Composer, SMW _always_ thinks it's installed - even for users who have no interest in using it. I see two main options here: patch SMW to get rid of the error message, or add some CSS to hide "errorbox" divs within the Special:Version page. (I think SMW is the only extension that adds an error message to Special:Version.)

A third option, of course, is to attempt to get the SMW developers to themselves remove this error message "upstream", but I don't know how likely that is to work, and it would probably be too later for this MW 1.39 release anyway. (Though it's a good idea, no matter what.)

**Comment by yaronkoren** [comment]
By the way, here is one way to hide the error message via CSS:

```
page-Special_Version .errorbox {
	display: none !important;
}
```

**Comment by jeffw16** [comment]
This isn't removed yet?? 100% support the CSS idea.

**Comment by yaronkoren** [comment]
I don't think the CSS is a good idea, actually, because it turns out that it doesn't always get applied - in the case of the "mobile view", for instance. I think a patch would be better, though CSS is better than nothing.

**Comment by yaronkoren** [comment]
I just installed SMW on a wiki running 1.39, and can confirm that it no longer displays that warning message if it's downloaded but not enabled. (Why the code to display the warning is still there in SMW, I don't know.) Anyway, I think this can be closed.
