### ISSUE TITLE
Clarify to users that $wgSMTP is required for mailing

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#145]
**Updated task**: Make it clear to admins that they will need to use an email service (i.e., by setting $wgSMTP) in order to have the wiki send emails. Information should be added in the following places:

- On the website, maybe in a new "Known issues" section
- In the CLI installer, as text that shows up at some point during installation
- On the wiki itself - in a warning message box that shows up, maybe at the top of the page, if $wgSMTP is not set, on some set of pages and for some set of users.

**Comment by jeffw16** [comment]
I don't think it should depend on the host OS.

**Comment by yaronkoren** [comment]
Cc @freephile

**Comment by yaronkoren** [comment]
After discussion, it seems pretty clear that doing default mailing from within Canasta is generally a bad idea, and might not be doable at all. (To some extent, it's a bad for _any_ wiki.) So we're changing the focus here - instead of trying to get default mailing working, we will try to make it clear to all admins that they will need to use an email service (i.e., by setting $wgSMTP) in order to have the wiki send emails. Information should be added in the following places:

- On the website, maybe in a new "Known issues" section
- In the CLI installer, as text that shows up at some point during installation
- On the wiki itself - in a warning message box that shows up, maybe at the top of the page, if $wgSMTP is not set, on some set of pages and for some set of users.

Presumably all three of these should link to the following URL as part of their explanation: https://www.mediawiki.org/wiki/Manual:$wgSMTP

**Comment by yaronkoren** [comment]
@freephile - are you planning to do all three of these subtasks? For the website, by the way, I would think the best place to put this information currently is in the "[Troubleshooting](https://canasta.wiki/faq/#troubleshooting)" section, which you can edit [here](https://github.com/CanastaWiki/Canasta-Documentation/blob/main/troubleshooting.md).
