### ISSUE TITLE
wfLoadExtension(), wfLoadSkin() should display Canasta-specific error message if JSON file not found

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#146]
With the new setup we have for the extensions/ and skins/ directories, there's a very real chance that the following could happen: an admin adds a new extension to their user-extensions/ directory (or same with a skin), reloads the wiki in the browser, and is surprised to see that the wiki has crashed because this extension (or skin) is not found. It would be good if the error message output by wfLoadExtension() and wfLoadSkin() were modified to be more Canasta-specific, i.e. if text were added to it like "Because this is a Canasta installation: if you added this extension [or skin] to the user-extensions/ [or ..skins] directory, you first need to [do whatever action] in order for the wiki to see it."

The ideal way to do this would be to somehow override these functions, but I don't know if this is possible. Having looked through the code, I think the best solution may actually be just to patch MediaWiki, by changing the line of code that outputs an error message in ExtensionRegistry::queue().

**Comment by yaronkoren** [comment]
This might not be necessary if the following is done:
- #159

**Comment by jeffw16** [comment]
Is this still really necessary?

**Comment by yaronkoren** [comment]
No. :)
