### ISSUE TITLE
Errorr install the canasta with CLI

### ISSUE THREAD

**Issue by lotusccong** [CanastaWiki/Canasta#147]
I am running on Linux debian11 5.10.0-19-amd64
When I run the sudo canasta create -i canastaId -n example.com -w Canasta Wiki -a admin -o docker-compose, it has the below error message:

debian@debian11:~$ sudo canasta create -i canastaId -n example.com -w Canasta Wiki -a admin -o docker-compose
2022/11/03 11:33:56 error statting /root/.config/canasta (stat /root/.config/canasta: no such file or directory)
Enter the admin password (Press Enter to autogenerate the password): 
Setting up Canasta

Any idea what is when wrong during the installation process ?

**Comment by jeffw16** [comment]
Thanks for the bug report. This is a known issue, but it would belong in https://github.com/CanastaWiki/Canasta-CLI
