### ISSUE TITLE
Remove LocalisationUpdate extension

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#149]
We don't actually have to do anything for this, since LocalisationUpdate is in Canasta because it was bundled with MediaWiki 1.35, and it was removed from MW in version 1.38. Apparently the Wikimedia Foundation people want to just end this extension altogether:

https://phabricator.wikimedia.org/T300498

Still, if anyone thinks this extension should be kept in the MW 1.39 version of Canasta, this is your chance to make your case.

**Comment by jeffw16** [comment]
No objections from me.

**Comment by jeffw16** [comment]
Seeing as there are no objections, I'm closing this task as done, since there's nothing we have to do to make this change.
