### ISSUE TITLE
Remove, or fix, GoogleAnalyticsMetrics extension for MW 1.39

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#150]
The GoogleAnalyticsMetrics extension seems like it can't work yet with MediaWiki 1.39, because it uses monolog 1.x, while MediaWiki 1.39 requires monolog 2.2. Here's the error message when you try to install it via Composer:

Your requirements could not be resolved to an installable set of packages.

```
  Problem 1
    - Root composer.json requires google/apiclient 2.2.1 -> satisfiable by google/apiclient[v2.2.1].
    - google/apiclient v2.2.1 requires monolog/monolog ^1.17 -> found monolog/monolog[1.17.0, ..., 1.27.1] but it conflicts with your root composer.json require (^2.2).
```

So, I assume this extension needs to be fixed, or removed from Canasta.

CC @tosfos

**Comment by tosfos** [comment]
WikiTeq is in the process of updating all our maintained extensions for 1.39. I bumped priority on this one. We'll let you know once it's resolved.

**Comment by yaronkoren** [comment]
Okay, cool. By the way, I just happened to see this - Google's "Universal Analytics" is going away next year:

https://support.google.com/analytics/answer/11583528?hl=en

I have no idea if this affects this extension, but I figured I should note it.

**Comment by jeffw16** [comment]
Right now it's scheduled for removal from Canasta 1.3.0 (which is waiting for MW 1.39 to release) but we can always add it in Canasta 1.3.1.

**Comment by tosfos** [comment]
The upstream patch has been merged. https://gerrit.wikimedia.org/r/c/mediawiki/extensions/GoogleAnalyticsMetrics/+/855972

**Comment by yaronkoren** [comment]
Excellent! Is the monolog version already updated, or is this patch preparing for that? (Basically, I want to know if I can close this issue.)

**Comment by tosfos** [comment]
My guess is that Composer will already pull the correct monolog version. We still need to issue a PR to include the new extension version though. https://github.com/CanastaWiki/Canasta/blob/975a5b39f132c2a3658c67a181f2375563a5fb9d/Dockerfile#L284

**Comment by jeffw16** [comment]
@yaronkoren Simply making a PR for Canasta to use the Google Analytics Metrics commit hash that @tosfos linked to will be sufficient for this issue to be resolved.

**Comment by yaronkoren** [comment]
Alright, that sounds good. Well, I think as far as the underlying code is concerned, this issue is now resolved.

**Comment by yaronkoren** [comment]
By the way, I just discovered that Canasta already has a patch to get rid of its monolog version requirement, just so GoogleAnalyticsMetrics can work:

https://github.com/CanastaWiki/Canasta/blob/master/_sources/patches/core-fix-composer-for-GoogleAnalyticsMetrics.diff

So I guess this fix wasn't really necessary, since we could always have just kept/updated this patch. But this solution is definitely better.
