### ISSUE TITLE
initial creation of wiki fails at install.php with waiting 60 seconds for db:3306

### ISSUE THREAD

**Issue by silverhikari** [CanastaWiki/Canasta#151]
as stated above creating a wiki with the following command "sudo canasta-cli create -v -i wiki1 -w "wiki" -a admin -o docker-compose"(the reason for the change in name of the executable is that a created a package that installs the latest version of contasta, so that it can be removed by the package manager but beyond that everything is the same). the program fails at "waiting 60 seconds for db:3306" repeating.i have checked that the docker daemon is running and it can access containers.

docker : 20.10.21

docker-compose: 2.12.2

verbose log: https://paste.ee/p/SR6Fh

**Comment by jeffw16** [comment]
Without further context, can't reproduce this issue. Likely to do with Docker networking, but there's no way to tell.
