### ISSUE TITLE
Add TemplateWizard

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#152]
Developed and used by WMF, very ubiquitous on WMF projects.

https://www.mediawiki.org/wiki/Extension:TemplateWizard

**Comment by yaronkoren** [comment]
I suppose the reason it's not included is that we already recommend Page Forms to use for adding templates to pages. On the other hand, VisualEditor already lets you add free-form template calls to pages, especially with the TemplateData extension, which is also included in Canasta. So I suppose it makes sense to add this as well, even though it will (hopefully) be litte-used.
