### ISSUE TITLE
Update or remove Vector skin's "VectorGeneratedSkinData" patch

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#167]
Canasta contains a patch to the Vector skin, by @pastakhov, that adds the hook "VectorGeneratedSkinData" to the Vector skin's VectorTemplate.php file:

https://github.com/CanastaWiki/Canasta/blob/master/_sources/patches/skin-vector-addVectorGeneratedSkinDataHook.patch

This patch will not work any more with the MW 1.39 version of Canasta, because the file VectorTemplate.php no longer even exists, as far as I can tell. So the patch needs to be either updated or removed - depending, I assume, on whether that hook is still being used.

**Comment by pastakhov** [comment]
it is used in https://github.com/WikiWorks/FsHeader extension by FamilySearch.    But right now it seems the extension is not used. We'll clarify about the extension, most likely the patch should be removed.

**Comment by yaronkoren** [comment]
Yes - I can confirm that this extension (and this hook) are no longer used on FamilySearch, and thus that, as far as I know, no one is using  this hook.
