### ISSUE TITLE
Add UserPageViewTracker extension

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#172]
@sanjay-thiyagarajan recently made some fixes to the UserPageViewTracker to get it working better with MW 1.39:

https://www.mediawiki.org/wiki/Extension:UserPageViewTracker

It seems to work fine now, and it does some useful analytics. We've talked before about adding the Wiretap extension to Canasta - but it has several problems, one of which is being overly invasive about users' site activity. UserPageViewTracker seems like a good tool to use in its place.

**Comment by tosfos** [comment]
I agree
