### ISSUE TITLE
Add WatchAnalytics extension

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#177]
There has been a lot of interest in adding the WatchAnalytics extension, but it didn't seem to be well-maintained. With the [permission](https://github.com/enterprisemediawiki/WatchAnalytics/issues/124) of the WatchAnalytics developers, we copied the extension's code to the Wikimedia Git repository, and @sanjay-thiyagarajan got it working with MW 1.39. Here is the current documentation for it:

https://www.mediawiki.org/wiki/Extension:WatchAnalytics

Hopefully translations for it will start appearing soon, but I think it would be great to get this into Canasta, maybe even before that's done.

**Comment by tosfos** [comment]
Sounds good!

**Comment by jeffw16** [comment]
Per #205, this extension has been seconded by a member of the community, so now it can be considered for inclusion. Please discuss below. The discussion period ends in 2 weeks. If there are no further comments by then, the extension will be presumed to have been approved by the community and it will be slated for inclusion.

**Comment by olsonjaredm** [comment]
Strongly agree on inclusion. Thanks for everyone's work to get it updated; this is an important extension for wikis that rely on its interface for regular subject matter expert review of page changes and approved revisions.
