### ISSUE TITLE
Autositemap Extension

### ISSUE THREAD

**Issue by gitmapd** [CanastaWiki/Canasta#178]
This extension as a replacement for "mwsitemapgen.sh", it really simplifies things and really customizable.
The link for the documentation is https://www.mediawiki.org/wiki/Extension:AutoSitemap

**Comment by pastakhov** [comment]
> This extension as a replacement for "mwsitemapgen.sh"

I don't think so, this extension can work for extremely small wiki only. It resolves only one thing -  when you have a very small wiki and cannot run mwsitemapgen.sh automatically. In all other cases, it will not work well (at all).

**Comment by vedmaka** [comment]
I'd also vote against this, the `AutoSitemap` extension idea is nice and I think it works well for wiki running in a restricted environments (like shared hosting), however, there are two major issues why it should not be used for Canasta or any other containerised wiki:

* containerised wiki is not a restricted environment in a form that we can have parallel processing running inside a container
* it's not necessary that wiki being created is an empty wiki, it can have a pre-imported database with existing pages and these pages will be ignored by AutoSitemap completely until edited or moved
* the extension performs sitemap updates during page rendering, thus it does this synchronously and so adds to page loading time vs  `mwsitemapgen.sh` which runs in background and does not interfere with page rendering

**Comment by jeffw16** [comment]
Agreed with @vedmaka and @pastakhov

**Comment by tosfos** [comment]
Thanks for the suggestion! Looks like this won't move forward.
