### ISSUE TITLE
Remove SocialProfile patches

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#198]
Canasta currently includes two patches for the SocialProfile extension: social-profile-REL1_35.44b4f89.diff and SocialProfile-disable-fields.patch. The first is a security fix that was added to SocialProfile a while ago, while the second is a Canasta-specific addition (it adds the page Special:ManageFields, and makes some related changes). Regardless, they should both be removed, since they apply only to the MW 1.35 version of SocialProfile. If there's going to be a new version of the second patch, I would think it should be created separately.

**Comment by jeffw16** [comment]
btw, we should probably remove this extension entirely because @kizule said this extension isn't even compatible with 1.39.

@kizule could you please first confirm if this is the case, and if so, is anyone opposed to removing it?

However, as @yaronkoren said, this PR should be merged regardless.

**Comment by kizule** [comment]
I don't remember that I said something like this for this extension. If I told something like that, it's no longer true anyways.

Because https://www.mediawiki.org/wiki/Extension:SocialProfile is showing that it is compatible with 1.39+.

**Comment by kizule** [comment]
+1 from me as well for removing SocialProfile custom patches. :)

**Comment by yaronkoren** [comment]
Okay, I'm marking this as closed, because I just merged in the patch. I have no idea whether SocialProfile actually works with MW 1.39 - maybe no one does yet? But any discussion about removing it should probably take place elsewhere, maybe in issue #107 - which was closed, but could be re-opened.
