### ISSUE TITLE
Error setting up on Windows

### ISSUE THREAD

**Issue by WaqarTabish2807** [CanastaWiki/Canasta#199]
In the documentation, there were no particular steps for windows set. Can we do it on windows by any chance?

**Comment by jeffw16** [comment]
It depends. It is possible but not supported. I got it working on Windows, but even though I work for Microsoft, please don't interpret this as Windows being officially supported in any way. Please see [this mailing list post](https://groups.google.com/u/2/g/canasta-wiki/c/Ou_HIG_bjkc) for more info.
