### ISSUE TITLE
Extension relevance rating

### ISSUE THREAD

**Issue by WolfgangFahl** [CanastaWiki/Canasta#202]
#192  brought up the question of when an extension might be included in Canasta and when not

- Is it frequently useful?
How many wikis do actively apply this extension 
- Does it work ?

**Comment by jeffw16** [comment]
Related to #205. This issue, #202, is great to think about.

**Comment by freephile** [comment]
I think Canasta policy should be aware of, and informed by, the WMF policy for writing an extension that would be a candidate for inclusion in WMF wikis. That policy is at https://www.mediawiki.org/wiki/Writing_an_extension_for_deployment.  FYI, there is also a workboard issue to "improve the process" https://phabricator.wikimedia.org/T195244

Everybody, including requesters, should be aware that the review process can and inevitably will sometimes move at a glacial pace. Maintaining an individual ticket (or 'epic' plus sub-tasks) will at least record the process. (IOW, there is no guarantee of an expedient trial. Example: the Drafts extension was nominated in 2012 https://phabricator.wikimedia.org/T39992 and is not approved as of 2023) 

So, to start with, the relevance rating review process would include:

Does it meet the [General Prerequisites and Expectations](https://www.mediawiki.org/wiki/Writing_an_extension_for_deployment#General_prerequisites_and_expectations)?

- [ ] Documentation
- [ ] Hosting
- [ ] Issue Tracking
- [ ] Stewardship
- [ ] Localization
- [ ] Feature flag
- [ ] Unit tests
- [ ] Schema
- [ ] Compatibility
- [ ] Tested (did you try it with Canasta already?)
- [ ] Code reviewed / Security audits

On top of the traditional WMF guidelines for extension inclusion, Canasta requirements should be layered on top (or override).

If this were reduced to a formula, I believe some useful metrics include (in no particular order) with examples of a simple algorithm:

Where is it hosted? 
+1 for WMF official hosting (ie. Gerrit)
.5 for leading public forges (ie. GitHub GitLab)
-1 for public, but non-standard forges that don't at least integrate with MWF CodeSearch (e.g. "ACME Widgets company git server at git.acme.uk")

How many wikis use it?
ranking TBD; based on pure usage numbers

How many large wikis or wiki farms use it?
ranking TBD; 3 large wikis using an extension; or one distribution (e.g. BlueSpice) is more positive than finding an extension installed on 30 minor wikis.

**Comment by harej** [comment]
This is a good outline of recommendations. I am not sure that strictly all of them are needed in all of Canasta's use cases. Monolingual use cases of Canasta don't necessarily need extensions with internationalization requirements, and an extension that is otherwise known to work shouldn't be automatically disqualified for being short on unit tests.

I think usage on a major wiki deployment like Wikimedia or MIraheze is a good shortcut. Wikimedia in particularly is a good proxy as they hold extensions to very high standards of security and performance. I am not sure Miraheze is as discerning, but they are big enough that if something didn't work, it would likely be noticeable and thus disabled.

**Comment by freephile** [comment]
Addressing some concerns:
**Too rigorous**
I'm only suggesting that we follow the WMF example, not that the Canasta formula is the exact same, or could / should not relax certain aspects.

**Comment by freephile** [comment]
To be clear, I'm trying to define a policy that would be transparent and not entirely subjective. I'm advocating for a (non-exhaustive) list of metrics with some type of grading or evaluation criteria/formula assigned to each. Say there are 12 categories from stewardship to unit tests. Each would have some description of what constitutes a "good", "bad" or "neutral" rating in that category. Some categories almost certainly should count more than others. For instance, usage/inclusion in a wiki farm or 3rd party vendor product such as Miraheze or Blue Spice should factor more heavily than whether issue tracking is on GitHub. 

Ideally, the relevance rating policy taken as a whole would allow anyone to judge (impartially) how well an extension meets the quality standards of the project.  

Final decision authority on whether an extension is bundled or not rests with the project leaders. And AFAIK, the Canasta project already supports the notion that deployments can specify their own "local" extensions anyway.

**Comment by yaronkoren** [comment]
I can understand the idea of wanting to be more transparent and methodical, but at this point, I think subjective (or really, the aggregation of different people's subjective views) is really the only way to go. The simplest case that can be made against strict criteria, I think, is that, just looking at the current ~150 extensions in Canasta, I can't imagine that there's any set of criteria that would allow all of them in: some lack unit tests, some lack i18n, many are essentially maintained by one person, etc. Of course, that's not ideal, but that's just the situation we're in, and - though there are a few extensions that I personally wouldn't really care if they were removed - in general I think it's a good set of extensions. You could argue that these extensions are "grandfathered in", and criteria can still be used for _new_ extensions, but if the rules don't work for the current set of functionality, then presumably there's something wrong with the rules.

You could also argue that Canasta needs better quality control, better stewardship, etc. - and I wouldn't argue with any of that - but we have to deal with the resources we have.

**Comment by jeffw16** [comment]
I agree completely with @yaronkoren.

At the end of the day, we are trying to improve Canasta. This seems like more red tape to me. Red tape that is unnecessary and will stymie progress.

I proposed the current extension nomination process in #205 out of a necessity and from input from community members. (I want to make it very clear that I would get rid of #205 if I could, but it's proven necessary and will continue to be necessary, given the number of community members Canasta currently has.) It has worked just fine for now. It's not really a stringent policy with any computations that definitively result in a yes/no determination.

Yaron said:

> we have to deal with the resources we have

and I agree emphatically. I am a pragmatist and I don't think it's pragmatic to add a Wikimedia Foundation-style level of bureaucracy for such a small, fledgling project. Getting bogged down in regulations is a great way for innovation to die.

If we have a problem with the process in #205 that needs to be refined, let's talk about it when we encounter an issue. Let's not fix what ain't broke.

**Comment by bawolff** [comment]
>  (IOW, there is no guarantee of an expedient trial. Example: the Drafts extension was nominated in 2012 https://phabricator.wikimedia.org/T39992 and is not approved as of 2023)

FWIW, extension deployment at WMF has a lot of behind the scenes steps that are not obvious. The main take away from Ext:Drafts bug should not be that the process is "slow" (which it often is), but that it didn't have sufficient buy-in from the right behind the scenes people, so was left to languish.

**Comment by yaronkoren** [comment]
I think it's safe to close this issue. These are all good criteria to take into account when reviewing extensions, but it doesn't look like there's any way to create actual rules based on these, so it doesn't seem like there's anything actionable here.
