### ISSUE TITLE
Refining procedure for requesting inclusion of extensions and skins into Canasta

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#205]
Proposing a new workflow for including new extensions and skins into Canasta:

- Extensions and skins should be nominated at https://github.com/CanastaWiki/Canasta/issues/new, with one issue per extension or skin being proposed. If a group of extensions are being nominated at the same time, an additional issue should be created for tracking purposes for all of the "subissues" each containing an extension's proposal.
- Nominated extensions should be seconded by someone else before the extension can be considered for inclusion.
- Several different significant wikis should be using this extension before it is proposed, ideally on Canasta to demonstrate it is compatible.
- Optional but recommended: Thorough testing and code review should be done by someone else other than the nominator to prove that it's production ready. (For instance, there shouldn't be any log spam.)
- Discussions about supporting or opposing inclusion should happen on the issue for proposing the extension. These discussions should follow the parameters governing Canasta inclusion, listed below. The consensus of that discussion will be considered as approval/disapproval for the inclusion. A reasonable time (~2 weeks) should be given for the public commenting period.
- If approved, someone should submit a PR to include the extension or skin. If no volunteers wish to make the PR, the extension and skin won't be added until someone makes the PR.

Inclusion criteria for extensions:
- Must be open source and free to use with a reasonable license (i.e. MIT, GPL, Affero).
- Actively maintained, both currently and in the foreseeable future.
- Relatively established and proven to work well (and interact with other extensions well) in production wikis.
- Reasonably relevant to a significant number of Canasta users, not just a small subset.
- In general, it should at least provide slightly different functionality. If the functionality is deemed too similar to an existing extension, then the extension should not be included.

----

This procedure in and of itself is also a proposal. Please feel free to comment below if you have suggestions on revising the above contents. Thanks!

**Comment by yaronkoren** [comment]
I'm always wary of too much bureaucratic regulation, especially when there's no infrastructure to support it, but I think the overall concept here is good, and the process details, like requiring "seconding", and the two-week commenting period, seem to make sense. I do have a few comments, though:

- "Several different significant wikis should be using this extension" seems redundant with "Relatively established and proven to work well" - I would think only one of those is necessary. (Though I agree with the gist of it.)
- Kind of a minor point, but I think "the extension and skin won't be added until someone makes the PR" doesn't need to be said.
- I don't think "Reasonably relevant to most Canasta users, not just a small subset" should be a criterion. In general of course it makes sense, but Canasta does include various extensions that would only ever be useful to a small subset of users: MintyDocs, GoogleDocCreator, UniversalLanguageSelector, etc.
- Maybe surprisingly, I don't think "The developer(s) of the extension don't object to its inclusion" should be a criterion either. We didn't ask any of the developers of the extensions and skins currently in Canasta for their permission, and I don't see why someone's objection to their work being included in Canasta should bother us. There may be some cases where this would really affect the decision for one reason or another, but that seems like it should be handled on a case-by-case basis, as opposed to a hard rule.

**Comment by jeffw16** [comment]
Hey Yaron, I actually think we agree on more points than it may seem at first glance.

> I'm always wary of too much bureaucratic regulation, especially when there's no infrastructure to support it,

I completely agree with you here, Yaron. I don't enjoy coming up with new rules either, but from the recent discussions and gridlock, I think we have reached the point where these guidelines are necessary to resolve the gridlock.

> Kind of a minor point, but I think "the extension and skin won't be added until someone makes the PR" doesn't need to be said.

Although it sounds obvious, I added this in because I don't want people to think they can just create proposals and then feel entitled that someone else will be nice and add it in. As you mentioned, there's no infrastructure to support it; we're all busy with other things and there should be no expectation that any of us will add it (unless it's us doing the proposing, of course). The intention behind this point is: if you want it, then do it yourself or find someone to do it, but don't expect it'll be done for you by a maintainer. This is of course not a very rosy statement but reflects the reality of the project.

> I don't think "Reasonably relevant to most Canasta users, not just a small subset" should be a criterion. In general of course it makes sense, but Canasta does include various extensions that would only ever be useful to a small subset of users: MintyDocs, GoogleDocCreator, UniversalLanguageSelector, etc.

First of all, let me clarify that I would support all of those extensions you mentioned here to be bundled. Actually, I would argue those extensions would be reasonably relvant to most Canasta users. Perhaps instead of `most Canasta users`, it could be replaced with `a significant amount of Canasta users`. I'll go ahead and make the verbiage change, but I will entertain even more changes if necessary.

> Maybe surprisingly, I don't think "The developer(s) of the extension don't object to its inclusion" should be a criterion either. We didn't ask any of the developers of the extensions and skins currently in Canasta for their permission, and I don't see why someone's objection to their work being included in Canasta should bother us. There may be some cases where this would really affect the decision for one reason or another, but that seems like it should be handled on a case-by-case basis, as opposed to a hard rule.

I added this because it's nice to do. I don't anticipate this happening, but from today's discussion about EmailLogger (which I wrote), I felt it was at least nice to be heard—as the extension author—whether the extension should be included or not. Obviously, there's nothing legally stopping us from going against their will if they released it under GPL or MIT. If it's an extension owner playing politics then I don't think this should be adhered to. But if there's legitimate reasons against inclusion, I feel like it'd be nice to listen to. Anyway, I'm fine with removing this bullet point.

**Comment by yaronkoren** [comment]
Well, in the case of EmailLogger, you were the one who (originally) wanted it to be added, so it was sort of the opposite scenario of what we're talking about.

**Comment by jeffw16** [comment]
Embarrassingly enough, I did not add that extension to the list I copied from and didn't verify the entire list. The rest of the list looked good to me, but I forgot to remove EmailLogger.

**Comment by bawolff** [comment]
> Must be open source and free to use with a reasonable license (i.e. MIT, GPL, Affero).

It should be noted that lots of corporations object to AGPL software. I think most of the time it is unreasonable objections, but if corporate world is the target here, that is something to keep in mind.

**Comment by yaronkoren** [comment]
Personally, I would be uncomfortable adding an Affero/AGPL extension to Canasta, whether my fears are justified or not. Thankfully it hasn't come up as an issue yet.

**Comment by yaronkoren** [comment]
Exactly a year later (!), I'm closing this because it's no longer actionable. We've integrated the concept of every extension or skin needing to be nominated and seconded into our methodology, which was the main thing here.
