### ISSUE TITLE
rsvg support

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#21]
MyWikis recently had a client report to us that ImageMagick was incorrectly thumbnailing some of their SVG files. Following in the Wikimedia Foundation's footsteps, we switched to using rsvg and the results are great. It may be a good idea to add rsvg support for Canasta; this would mean setting SVG thumbnail generation to using rsvg, like so:

```
$wgSVGConverter = 'rsvg';
```

**Comment by amalpaul54111** [comment]
Can I work on this Issue? I am just starting out on contributing to this project.

**Comment by jeffw16** [comment]
@amalpaul54111 Thanks for your interest! Yes, absolutely.

`rsvg` will need to be added to the image. Installing rsvg will need to be done within the Dockerfile.

Please see this page for more info on how rsvg works in MediaWiki: https://www.mediawiki.org/wiki/Manual:$wgSVGConverters

**Comment by amalpaul54111** [comment]
Thanks for your help.

**Comment by yaronkoren** [comment]
This seeems to have been completed back in June...
