### ISSUE TITLE
Add Extension:TemplateSandbox

### ISSUE THREAD

**Issue by harej** [CanastaWiki/Canasta#240]
Used on both Wikimedia and Miraheze, TemplateSandbox lets you preview pages with sandbox versions of templates. Useful if you do a lot of work around templates.

<https://www.mediawiki.org/wiki/Extension:TemplateSandbox>

**Comment by yaronkoren** [comment]
I can see how this would be useful for wikis that have the "Template:" namespace locked away for regular users - it seems reasonable.
