### ISSUE TITLE
Bind for 0.0.0.0:443 failed: port is already allocated

### ISSUE THREAD

**Issue by datawiki** [CanastaWiki/Canasta#241]
Can you run two separate Canasta containers in wsl2 docker? 

Caddy automatically binds 443, so changing the entry port from 80 to 8081 in the .env has no effect. 

Error response from daemon: driver failed programming external connectivity on endpoint can8081-caddy-1 (......): Bind for 0.0.0.0:443 failed: port is already allocated.

**Comment by jeffw16** [comment]
No, this use case is not supported and we don't intend to add support for it.

**Comment by yaronkoren** [comment]
I should note, though, that support for running multiple wikis within the same container is planned - see #57. This will hopefully be done this summer.
