### ISSUE TITLE
Add SemanticTasks extension

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#258]
https://www.mediawiki.org/wiki/Extension:Semantic_Tasks is needed for one of WikiWorks clients

**Comment by yaronkoren** [comment]
Ah, more fun with Composer. Could the EditNotify extension be used instead? I think it's a better solution in general - in part because it doesn't rely on SMW:

https://www.mediawiki.org/wiki/Extension:EditNotify

Or is it too late to switch, for that client?

**Comment by vedmaka** [comment]
I assume not too late, but I don't think EditNotify can be a replacement. EditNotify requires users to be explicitly specified on configuration. Thus, it's unable to dynamically determine recipients based on a semantic property (template param value)

**Comment by yaronkoren** [comment]
That's true... well, given that, I think it makes sense to include this extension. Its inclusion should probably be re-evaluated if/when Canasta offers support for adding extensions via Composer. (I think, long-term, the better solution for handling notifications and workflow like this is to add to EditNotify one or two parser functions, to allow for defining the "listeners" for any page - but that's a subject for another day.)
