### ISSUE TITLE
SSL trouble

### ISSUE THREAD

**Issue by MarioOsswald** [CanastaWiki/Canasta#271]
I have a test environment on Ubuntu 22.04 in a virtualbox with internet access, but not directly attached and followed the installation advices to get Docker and Canasta CLI, without errors.

As I'm not very familiar with docker, so I can't manage to add the ssl certificate for the enclosed Apatche image and I guess, canasta will (and can) not get the certs for me.

Since its just testing at the moment, I've configured http-only access both in .env and in LocalSettings.php.
Did restart canasta instance, rebooted the server, but my browser replies always SSL_ERROR_INTERNAL_ERROR_ALERT (Chrom, Firefox, Safari). I have no strict https only policy.

**Comment by jeffw16** [comment]
Are you using the Caddy container at all? The Apache container is not really supposed to be serving HTTPS. We've decided to go with using Caddy as the TLS termination proxy, and all other setups are to be done at your own risk without support (i.e. expert mode).
