### ISSUE TITLE
SemanticTasks can be enabled during initial setup but breaks the wiki

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#276]
Steps to reproduce:

* Fresh https://github.com/CanastaWiki/Canasta-DockerCompose instance (not via CLI)
* Image version `1.39.1-20230816-8f153da` ( which is `latest` by now )
* Run wiki setup wizard and pick `SemanticTasks` when asked what extensions to enable

Expected:

* Navigate to the wiki and see a homepage

Actual:

* Navigate to the wiki and see `Error: The Semantic Tasks extension requires the Semantic MediaWiki extension to be installed and enabled.`

Note: `SemanticMediaWiki` is not bundled with the image now, so selecting it at the wizard extensions picking step is impossible. Probably `SemanticTasks` need to be removed from the wizard

**Comment by yaronkoren** [comment]
Is this now fixed, like issue #277 was?

**Comment by yaronkoren** [comment]
I'm assuming this was fixed, so I'm closing it now - feel free to re-open if not.
