### ISSUE TITLE
SemanticFormsSelect can be enabled via setup wizard but does not work

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#277]
Steps to reproduce:

* Fresh https://github.com/CanastaWiki/Canasta-DockerCompose instance (not via CLI)
* Image version `1.39.1-20230816-8f153da` ( which is `latest` by now )
* Run wiki setup wizard and pick `SemanticFormsSelect` and `PageForms` when asked what extensions to enable
* Create a test form for SFS and navigate to `Special:FormEdit/Test/Test`

```
<includeonly>
{{{for template|Test}}}
{{{field|Test|input type=SF_Select|query=((Category:Protocol));format~list;sep~,;link~none;headers~hide;limit~500}}}
{{{end template}}}
</includeonly>
```

Expected:

* Form is displayed with an SFS input

Actual:

* `Error: Class 'SMWQueryProcessor' not found` exception is displayed

Note: `SemanticMediaWiki` is not bundled with the image now, so selecting it at the wizard extensions picking step is impossible. Probably `SemanticFormsSelect` need to be removed from the wizard

**Comment by yaronkoren** [comment]
What do you mean by Semantic MediaWiki not being bundled with the image?

**Comment by vedmaka** [comment]
I mean that due to https://github.com/CanastaWiki/Canasta/pull/270 SMW is not bundled with the image anymore

**Comment by yaronkoren** [comment]
That's not good that SMW is not getting included. It should be there in composer.local.json, and then composer.local.json gets included in composer.canasta.json. Where is this failing, do you know?

**Comment by vedmaka** [comment]
Fixed by https://github.com/CanastaWiki/Canasta/pull/280
