### ISSUE TITLE
SemanticDrilldown can be enabled via setup wizard but does not work

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#278]
Steps to reproduce:

* Fresh https://github.com/CanastaWiki/Canasta-DockerCompose instance (not via CLI)
* Image version `1.39.1-20230816-8f153da` ( which is `latest` by now )
* Run wiki setup wizard and pick `SemanticDrilldown` when asked what extensions to enable

Expected:

* Navigate to `Special:BrowseData` and see the drill-down UI

Actual:

* Empty page is displayed

Note: `SemanticMediaWiki` is not bundled with the image now, so selecting it at the wizard extensions picking step is impossible. Probably `SemanticDrilldown` need to be removed from the wizard

**Comment by yaronkoren** [comment]
Is this now fixed, like issue #277 was?

**Comment by yaronkoren** [comment]
I assume this was fixed, so I'm closing it now.
