### ISSUE TITLE
Need Help: Sudoer Policy Errors on Wikitech Cloud VPS with Canasta 2.0

### ISSUE THREAD

**Issue by chl178** [CanastaWiki/Canasta#281]
Hello everyone,

I've initiated testing on Canasta 2.0's farm feature using the Wikitech Cloud VPS. Regrettably, I'm running into issues when trying to use sudo. Specifically, when I attempt to add sudoer policies via Horizon, it leads to errors. Has anyone previously encountered this, or does anyone have a solution or workaround? Any guidance would be greatly appreciated.

Thanks in advance!

I follow the [official guidance](https://wikitech.wikimedia.org/wiki/Help:Sudo_Policies) to add the sudoer policy.
![image](https://github.com/CanastaWiki/Canasta/assets/116774313/94577624-2517-407c-9b9d-7a4eb86548aa)
The errors:
![Screenshot from 2023-08-21 17-19-04](https://github.com/CanastaWiki/Canasta/assets/116774313/70964fb2-f222-4c22-9615-ae3cef1ea75f)
![Screenshot from 2023-08-21 17-17-29](https://github.com/CanastaWiki/Canasta/assets/116774313/7b41bf7a-2df7-476a-bdd2-45ef226a4fb3)

And when I was trying to solve it by using the instance interface directly, I found that the interface was always at loading status.
![Screenshot from 2023-08-21 17-21-45](https://github.com/CanastaWiki/Canasta/assets/116774313/f6ca90ea-80a0-4862-8943-eaa3273db40c)

**Comment by chl178** [comment]
@vedmaka, @cicalese, given your expertise, I was wondering if you might have come across this issue or have any suggestions?  Your guidance would be invaluable at this juncture.

**Comment by cicalese** [comment]
I have not had to configure sudo access on my WMCS projects. As a project member, I get sudo by default. What project roles are you assigned if you navigate to Access > Project Access?
