### ISSUE TITLE
Make MediaWiki Docker image the base image for Canasta

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#289]
It seems to make sense, if it's feasible, to switch to using the official MediaWiki Docker image as the base for Canasta. As I understand it, this would involve replacing the line "FROM debian:11.7" at the top with something like "FROM mediawiki:1.39", and then removing most of about lines 16-97 of the Dockerfile - which install MediaWiki, the LAMP stack, and a bunch of Linux commands like zip and git - since the MediaWiki Docker image already has most of them. (Though not everything: it doesn't include Vim, for instance. So some of those lines would need to be kept.)
	
Links for the Docker image:

- [Official page](https://hub.docker.com/_/mediawiki)
- [mediawiki.org page](https://www.mediawiki.org/wiki/MediaWiki-Docker)
- [Code on GitHub](https://github.com/wikimedia/mediawiki-docker) (yes, the whole repo is somehow a fork)
	
Any thoughts on this?

**Comment by yaronkoren** [comment]
By the way, I did an informal analysis - as far as I can tell, these are the commands and libraries in Canasta that are _not_ in the official MediaWiki image:
- inotify-tools
- software-properties-common
- apt-transport-https
- wget
- msmtp
- msmtp-mta
- patch
- vim
- mc
- ffmpeg
- iputils-ping
- unzip
- gnupg
- default-mysql-client
- rsync
- lynx
- poppler-utils
- php7.4-cli
- php7.4-gd
- php7.4-xml
- php7.4-redis
- php7.4-zip
- php7.4-fpm
- libapache2-mod-fcgid

	
I could be wrong about some of these. But assuming this list is basically accurate: some of these are definitely necessary - ffmpeg is needed by the TimedMediaHandler extension, for instance - though others could possibly just be dropped. I don't know if Canasta really benefits from including the Lynx web browser, for example. On the other hand, there's no real harm in including all of them.

**Comment by jeffw16** [comment]
It seems obvious we should have done this from the start, right?

Well, we didn't because we didn't want to depend on something that:

- Over which we have zero control and could go unsupported/changed heavily without notice at any time
- Is only officially meant for developer environments
- Is meant to work with SQLite officially
- Has a very different approach to how voluming in files work
- In a nutshell, is internally organized very differently from Canasta

**Comment by yaronkoren** [comment]
Thank you for the response - that's very interesting. I agree that there's an obvious risk there, but I'm especially curious about the 4th point. Can you explain how MediaWiki-Docker's voluming-in of files differs from Canasta's?

**Comment by tosfos** [comment]
Referencing the related #154

**Comment by jeffw16** [comment]
@cicalese has another proposal that I think is a lot more feasible: using the PHP container as a base image.

In the meantime, closing it for the reasons I provided on September 5, 2023.
