### ISSUE TITLE
Surplus symlinks are created within extensions directories

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#300]
Steps to reproduce:

* Gear up a new stack of Cansta
* Ensure your local `extensions` directory is mounted into the Cansta container at `/var/www/mediawiki/w/user-extensions`
* Pus some extension (say, Survey) into `extensions` directory
* Start the container

Expected:

* No new files were created within the extension directory on the host

Actual:

* A symlink under the extension name is created within the extension directory on the host:

```bash
ls -al extensions/Survey
...
Survey -> /var/www/mediawiki/w/canasta-extensions/Survey/
...
```

**Comment by yaronkoren** [comment]
I believe this was fixed a while ago, with #366.
