### ISSUE TITLE
Images directory writable status not checked on container start

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#325]
When the container starts, it only checks for `MW_VOLUME` to be writable and not for the `images` directory. Because of this, if for any reason (e.g., images migration) the directory is not writable, it will stay not writable after the start and will lead to issues with image uploads and thumbnail generations until manually fixed on the host.

The proposal is to check for `images` directory writable status on start and change permissions as needed like it's done in Taqasta https://github.com/WikiTeq/Taqasta/blob/master/_sources/scripts/update-images-permissions.sh#L11

**Comment by yaronkoren** [comment]
I believe this is now fixed, thanks to some recent merging-in of WikiTeq code to the main Canasta branch.
