### ISSUE TITLE
Consider adding extensions demoed at SMWCon 2023

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#340]
The recent SMWCon Fall 2023 had a surprisingly large number of new-ish extensions being demonstrated, some of which seemed quite compelling - so I thought it would be useful to list them all here, to see if there's strong support for adding any of them to Canasta. If it turns out that any of them do have support, then a separate issue should probably be created for each of those extensions.

By the way, this isn't all the extensions that were demoed - some of them have not been released yet, some (like [OpenSemanticLab](https://www.mediawiki.org/wiki/Extension:OpenSemanticLab)) are still experimental, and some (like [Semantic Structured Discussions](https://www.mediawiki.org/wiki/Extension:Semantic_Structured_Discussions)) are pretty much obsolete already.

Here is the list of includable extensions, as far as I can tell:

From Wikibase Solutions:
- [WSStats](https://www.mediawiki.org/wiki/Extension:WSStats)
- [TimedNotify](https://www.mediawiki.org/wiki/Extension:TimedNotify)

From Hallo Welt (they have been churning out extensions!):
- [PreToClip](https://www.mediawiki.org/wiki/Extension:PreToClip)
- [SectionAnchors](https://www.mediawiki.org/wiki/Extension:SectionAnchors)
- [StandardDialogs](https://www.mediawiki.org/wiki/Extension:StandardDialogs)
- [ContainerFilter](https://www.mediawiki.org/wiki/Extension:ContainerFilter)
- [Workflows](https://www.mediawiki.org/wiki/Extension:Workflows)
- [ContentStabilization](https://www.mediawiki.org/wiki/Extension:ContentStabilization)
- [Forms](https://www.mediawiki.org/wiki/Extension:Forms) (I believe both ContentStabilization and Forms are required by Workflows, even though the documentation doesn't say that)
- [AtMentions](https://www.mediawiki.org/wiki/Extension:AtMentions)
- [Checklists](https://www.mediawiki.org/wiki/Extension:Checklists)
- [DateTimeTools](https://www.mediawiki.org/wiki/Extension:DateTimeTools)
- [SimpleTasks](https://www.mediawiki.org/wiki/Extension:SimpleTasks)
- [OOJSPlus](https://www.mediawiki.org/wiki/Extension:OOJSPlus) (required by both Workflows and AtMentions?)

From WikiTeq:
- [InlineComments](https://www.mediawiki.org/wiki/Extension:InlineComments)

InlineComments is in a separate category from the others - it wasn't actually demoed, but it was mentioned in a talk by Robin from ArchiXL about SmartComments (or whatever it will be called), their own inline commenting extension which hasn't been released yet. InlineComments is also new, though (only six months old), and it seems to have one advantage over SmartComments, which is that comments appear right on the page, instead of showing up as little icons that need to be clicked to see the comment.

Does anyone want to speak up for including any of these?

**Comment by freephile** [comment]
I don't think WSStats should be included.

I do think InlineComments should.

**Comment by yaronkoren** [comment]
InlineComments does seem like a good one to add, especially if/when it reaches "stable" status. I think there's also a strong argument for adding in the Checklists extension.

**Comment by yaronkoren** [comment]
I created a task for adding the InlineComments extension, at #362. It would be ironic if the only - or at least the main - extension to be added as a result of SMWCon talks would be one that wasn't even demoed at SMWCon, but that may be how things turn out.

**Comment by tosfos** [comment]
Is there a reason to consider it? It requires new SQL tables, has the SMW dependency and seems not quite ready yet. Any advantages?

**Comment by yaronkoren** [comment]
@tosfos - sorry, I was sure I had responded to this already, but apparently not. Anyway, I don't know of any advantages that SmartComments has over InlineComments, though on the other hand I don't really know how SmartComments looks or functions. (There was a demo of it at SMWCon, but maybe it has changed since then.) I really just wanted to note it for the sake of completeness with the overall issue.

**Comment by yaronkoren** [comment]
Closing this issue - I think all of these extensions have been considered to some extent, and at the moment there's only consensus for adding one of them: InlineComments. If anyone is interested in any of the rest of them, please create a separate issue for them.
