### ISSUE TITLE
Use GitHub mirrors instead of Gerrit

### ISSUE THREAD

**Issue by jamesmontalvo3** [CanastaWiki/Canasta#35]
Recommend using GitHub mirrors for WMF resources. See https://github.com/enterprisemediawiki/meza/pull/1061

**Comment by jamesmontalvo3** [comment]
I suppose it's not worth the effort until it presents an issue to you. We saw it when we started testing more conditions in CI, and hitting Gerrit a lot caused issues. Also in automated deploys to dev/test/production environments in succession would work for dev and test then fail in production, which sucked.

**Comment by jeffw16** [comment]
I think this is a good idea and I think we should do this when we have time. Thank you James!

**Comment by Ayman161803** [comment]
I would like to work on this. Can I please have this assigned?

**Comment by yaronkoren** [comment]
Yes, definitely! Go ahead.

**Comment by adi-code22** [comment]
Is it okay if I work with the same issue?, it seems like a good first issue.

**Comment by jeffw16** [comment]
In the interest of keeping things straightforward, let's keep it one person per task. Please try one of the other tasks suggested in #219. We value completion of harder tasks when selecting the GSoC contributor.

**Comment by bogisushrith** [comment]
Hello @jeffw16 , @yaronkoren , I would like to work on this issue. Could you please assign it to me, I noticed it has been assigned for two weeks.

**Comment by jeffw16** [comment]
@bogisushrith thanks for your interest. This issue already has a code complete PR. It's just awaiting final testing and approval for merging.

**Comment by yaronkoren** [comment]
@bogisushrith (and anyone else) - for those of you who are interested in the Canasta Google Summer of Code project, we have already had interest from a good number of qualified candidates, so we have decided to limit our selection to the group of people who have already submitted a PR in one way or another, to avoid other people wasting their effort. If you want to participate in this year's GSoC, I would say you should find another project, with the Wikimedia Foundation or elsewhere. On the other hand, if you just want to contribute to Canasta, contributions are always welcome!

**Comment by yaronkoren** [comment]
This was done, about six months ago.
