### ISSUE TITLE
Upgrade Canasta to PHP 8.1

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#352]
Canasta currently runs with PHP 7.4, which unfortunately has been end-of-life since November 2022, meaning that it no longer accepts security fixes. That's a big problem. Thus, we should upgrade to PHP 8.1 as soon as possible.

PHP 8.1 will itself be EOL in November 2024, but unfortunately that's the best we can do, because MW 1.39 does not yet officially support PHP 8.2 or higher. In fact, even the very latest MW version, 1.42, doesn't yet support PHP 8.2! You can see the Phabricator workboard to complete PHP 8.2 support [here](https://phabricator.wikimedia.org/project/view/6053/) - hopefully this will be done by the end of the year.

As discussed at #347, it appears that the ideal approach for this is to change Canasta to use php:8.1-apache as its base image, instead of debian:11.7. Since php:8.1-apache includes PHP, Apache and Debian, this change should allow for the Dockerfile to be simplified quite a bit. Hopefully this won't cause any problems with PHP-FPM or anything else.

A note about extensions and skins: there are some (like Page Forms and Cargo) that will need to be updated, because their latest versions have improved support for PHP 8. There may be others (possibly Semantic MediaWiki) that still don't fully work with PHP 8. For those, there's nothing much we can do - assuming they work at all, just include them and hope their remaining bugs are not too severe.

**Comment by tosfos** [comment]
Can this be close after #379 ?

**Comment by yaronkoren** [comment]
Oh yeah... I thought this was closed already.
