### ISSUE TITLE
The inotifywait function call was removed and /monitor-directories.sh is not running

### ISSUE THREAD

**Issue by pastakhov** [CanastaWiki/Canasta#363]
This commit https://github.com/CanastaWiki/Canasta/commit/f962d3db75f045fe5907ad1758ddc66525842ff9 removed (most likely by mistake) the line with `inotifywait &`  and  /monitor-directories.sh is not running in the docker container. When you add/remove an extension in the `user-extensions` folder, the symlinks are not updated.

**Comment by yaronkoren** [comment]
@pastakhov - thank you for finding that issue!! That's a major bug, and it definitely explains some behavior we have seen recently. We need to either re-add the call to inotifywait, or add monitor-directories.sh to the maintenance-scripts/ folder, so that it gets called automatically.
