### ISSUE TITLE
cp: target 'Wiki/Settings.php' is not a directory

### ISSUE THREAD

**Issue by jakejellinek** [CanastaWiki/Canasta#369]
I'm trying to install according to the documentation, I have run the bash script to install, and then when it comes to creating the containers etc. I run the suggested command line and it fails:-

root@docs:~# canasta create -i MyWiki -n docs.mydomain.org -w "My Documentation Wiki" -a admin -o compose

2024/03/07 14:15:13 Using /etc/canasta for configuration...
Enter the admin password (Press Enter to get saved password or, if one does not exist, autogenerate a password): 
Re-enter the admin password: 

⠋ Creating Canasta installation 'MyWiki'...  [0s] Successfully written to wikis.yaml
⠦ Creating Canasta installation 'MyWiki'...  [0s] cp: target 'Wiki/Settings.php' is not a directory

A fatal error occured during the installation.
Do you want to keep the files related to it? (y/n)

I'm using Ubuntu 22.04.4 LTS in a VM

**Comment by jakejellinek** [comment]
OK so I got this to work by changing "My Documentation Wiki" to "MyWiki" - I had thought it was the name of the Wiki, but it appears it is used as a directory name and the spaces were causing issues.

**Comment by yaronkoren** [comment]
@jakejellinek - thank you for reporting, and diagnosing, this problem. If spaces in a wiki name cause an error, that's a major bug - we will look into it.

**Comment by ImMarkP** [comment]
Hello!
I can confirm this behaviour on a Debian 12 x86-64 VM with 4096MB RAM and 2vCPU.

**Comment by labster** [comment]
This is a whitespace issue, I'm pretty sure, since I hit the same thing:

```
brent@MacBook-Pro ~/c/d/Canasta (master)> sudo canasta -v create -i flurble -w "Brumble Blag" -a admin -o compose
Password:
2024/09/08 23:12:50 Using /etc/canasta for configuration...
Setting verbose
Enter the admin password (Press Enter to get saved password or, if one does not exist, autogenerate a password):
Re-enter the admin password:
⠋ Creating Canasta installation 'flurble'...  [0s] Successfully written to wikis.yaml
Cloning the compose stack repo to /Users/brent/code/docks/Canasta/flurble
git clone https://github.com/CanastaWiki/Canasta-DockerCompose.git /Users/brent/code/docks/Canasta/flurble
Cloning into '/Users/brent/code/docks/Canasta/flurble'...
⠇ Creating Canasta installation 'flurble'...  [0s] Copying /Users/brent/code/docks/Canasta/wikis.yaml to /Users/brent/code/docks/Canasta/flurble/config/wikis.yaml
cp /Users/brent/code/docks/Canasta/wikis.yaml /Users/brent/code/docks/Canasta/flurble/config/wikis.yaml
Copying /Users/brent/code/docks/Canasta/flurble/.env.example to /Users/brent/code/docks/Canasta/flurble/.env
cp /Users/brent/code/docks/Canasta/flurble/.env.example /Users/brent/code/docks/Canasta/flurble/.env
⠇ Creating Canasta installation 'flurble'...  [0s] Copying /Users/brent/code/docks/Canasta/flurble/config/wikis.yaml to /Users/brent/code/docks/Canasta/flurble/.env
cp /Users/brent/code/docks/Canasta/flurble/config/SettingsTemplate.php /Users/brent/code/docks/Canasta/flurble/config/Brumble Blag/Settings.php
cp: Blag/Settings.php is not a directory
cp: Blag/Settings.php is not a directory

A fatal error occured during the installation.
Do you want to keep the files related to it? (y/n)
n
```

**Comment by jeffw16** [comment]
Thank you for the detailed logs @labster!

In that case, it indicates the wiki name is used to create the config directory. Yikes! We need to fix that.

**Comment by labster** [comment]
Actually I rebuilt Canasta-CLI from source and the error disappeared (and I got a new fatal much later in the process).  Curious.

[This line](https://github.com/CanastaWiki/Canasta-CLI/blob/6e4c9581be4893ab965b6a17bbc574fe7c9c05b2/internal/execute/execute.go#L38) looks wrong:
> 	cmd := exec.Command("bash", "-c", command+" "+strings.Join(cmdArgs, " "))

The commands should be passed directly to exec.Command, not joined as a single string.  I don't know enough Golang to help here, but you should see if you can unpack the cmdArgs array.

**Comment by labster** [comment]
Hey, I got it to fail on the first command :)

```
brent@MacBook-Pro ~/c/d/Canasta-CLI (main)> sudo canasta -v create -i 'flurble bubble' -w "Brumble Blag" -a admin -o compose
Password:
2024/09/09 00:10:40 Using /etc/canasta for configuration...
Setting verbose
Enter the admin password (Press Enter to get saved password or, if one does not exist, autogenerate a password):
Retrieved admin password from /Users/brent/code/docks/Canasta-CLI/.admin-password
⠋ Creating Canasta installation 'flurble bubble'...  [0s] Successfully written to wikis.yaml
Cloning the compose stack repo to /Users/brent/code/docks/Canasta-CLI/flurble bubble
git clone https://github.com/CanastaWiki/Canasta-DockerCompose.git /Users/brent/code/docks/Canasta-CLI/flurble bubble
fatal: Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --[no-]verbose    be more verbose
    -q, --[no-]quiet
      be more quiet
    --[no-]progress       force progress reporting
    --[no-]reject-shallow don't clone shallow repository
    -n, --no-checkout     don't create a checkout
    --checkout            opposite of --no-checkout
 ...
```

I am best human fuzzer.

**Comment by jeffw16** [comment]
Yeah agreed that it looks wrong :/

**Comment by yaronkoren** [comment]
Sorry for all the problems. There have been (as you might imagine) a few different issues described in this bug report and the comments, some of which have been fixed already. The latest one found is that having a space in a wiki ID leads to an error. That's a bug, of course - and the real issue is that the code should ensure that wiki IDs can only have alphanumeric characters, with no spaces or other punctuation. (Perhaps dashes and/or underscores should be allowed, though; I'm not sure.) Anyway, validation for the ID was just added, in this commit:

https://github.com/CanastaWiki/Canasta-CLI/pull/117

**Comment by labster** [comment]
The problem with the exec.Command() call is that any shell quoting you pass to canasta-cli will be clobbered by the call.  So if you have an argument with a space in it, it will look to bash just as if it were a seperate argument, because it doesn't know where the space comes from.  (Even worse things will happen if you pass in arguments with semicolons or redirection in it.)

If you can ensure that the only user input you pass is validated (i.e. alphanumeric wiki id) from the script, this is fine.  But generally passing arguments joined by spaces to the shell is an easy way to get security bugs.

**Comment by yaronkoren** [comment]
The security risk thing makes sense.

**Comment by yaronkoren** [comment]
Given that the whitespace stuff has all been fixed (as far as I know), I'm closing this issue. Anyone can feel free to create other bug reports, of course.
