### ISSUE TITLE
Error in setting Canasta in mac m1

### ISSUE THREAD

**Issue by shreyaansjain06** [CanastaWiki/Canasta#37]
I tried running the commands mentioned in Quick Setup, but it failed every time and gave this error
```
no matching manifest for linux/arm64/v8 in the manifest list entries
```
I resolved it by adding this command in the docker-compose file
```
platform: linux/amd64
```

**Comment by jeffw16** [comment]
Thanks for this. Would you kindly be able to create a pull request for this change?

**Comment by shreyaansjain06** [comment]
Sure I have done that, and also I want to contribute to this project as part of Gsoc22.
So are there some microtasks that needs to be completed? I am ready to do that

Thank You

**Comment by shreyaansjain06** [comment]
I have mailed you and waiting for further details and can you please point me to a beginner friendly issue so that i can understand the codebase while working on the issue

**Comment by yaronkoren** [comment]
Re-opening this issue - the previous patch made use of an "experimental" Docker feature, "platform", that doesn't always work. Alternate architecture support needs to be added in some other way.

**Comment by jeffw16** [comment]
In that case we would need to create another Dockerfile based on the AArch64 Debian base image.

**Comment by gitmapd** [comment]
> In that case we would need to create another Dockerfile based on the AArch64 Debian base image.

Hi, the image by oracle "arm64" or the version 8 should work.

**Comment by jeffw16** [comment]
Thanks for the insight. Are you referring to the image remaining debian but the tag changing to arm64?

**Comment by gitmapd** [comment]
`version: "3.8"
services:
  mysql:
    container_name: mycontainername
    image: mysql/mysql-server:8.0.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabasename
      MYSQL_ROOT_HOST: "%"
    command: --lower_case_table_names=1`

**Comment by jeffw16** [comment]
I guess we never got a clear answer about this: has anybody actually tried building the image on an AArch64 platform? Perhaps that was the issue all along.

**Comment by gitmapd** [comment]
> I guess we never got a clear answer about this: has anybody actually tried building the image on an AArch64 platform? Perhaps that was the issue all along.

Ah! Thats a different thing. Ill see what i can do.

**Comment by jeffw16** [comment]
Fixed now
