### ISSUE TITLE
Syntax Error, Canasta on Raspberry Pi 4B (Cortex-A72 (ARM v8))

### ISSUE THREAD

**Issue by ImMarkP** [CanastaWiki/Canasta#393]
## Describe the bug
**Summary**:
Running `sudo canasta` with any or no arguments results in the message` /usr/local/bin/canasta: 6: Syntax error: ")" unexpected`

**Description**:
Installed several times on two different Pi 4B boards (2GB and 4GB). Docker's "hello-world" reports that Docker is working. Canasta installation following https://canasta.wiki/setup/ seems to work fine with no issues. After installation, /usr/local/bin/canasta is 6418189 bytes and is dated April 19th at 16:52.

Running any combination of `sudo canasta <option>` gives the error described above. Running `canasta` without sudo gives the error "cannot execute binary file: Exec format error"

**Screenshots**: If applicable, add screenshots to help explain your problem.

![image](https://github.com/CanastaWiki/Canasta/assets/168062226/2ecaaf86-326a-4c2a-b509-4ea56704033e)

![image](https://github.com/CanastaWiki/Canasta/assets/168062226/202cb9a3-a489-4b30-a643-8393b9870843)

![image](https://github.com/CanastaWiki/Canasta/assets/168062226/9e39ab87-96c3-4c7e-b8bf-d38fb8798544)

**Steps to reproduce the behavior**:
1. Install Raspberry Pi OS Bookworm, 64-bit (standard)
2. Follow instructions from https://docs.docker.com/engine/install/debian/#install-using-the-repository to install Docker.
3. Follow "Recommended: CLI Installation" instructions from https://canasta.wiki/setup/
4. Run `sudo canasta` with any (or no) options.

## Expected behavior
Expected to be able to create a wiki, run `sudo canasta help`, etc.

## System info
_Please complete the following information:_
 - No wiki installed yet (unable to get that far)
 - Canasta version: current (as of 2024-04-24)
 - Installed extensions and versions: None
 - Any other context you think is appropriate to include here:
 - Hardware: Raspberry Pi 4B v1.1 (2GB), 1.2 (4GB), Quad-core Cortex-A72 (ARM v8)
 - OS: Raspberry Pi OS (Bookworm), 64-bit, standard image.
 - Kernel: 6.6.20+rpt-rpi-v8 (2024-03-07) aarch64
 - Running Wayland

**Comment by jeffw16** [comment]
I think this is an issue with the Canasta CLI's build pipeline having poor support for AArch64. I (unfortunately) have a Mac with "Apple Silicon" that runs on AArch64 too, so I face a very similar issue as you.

The way to get around this issue is, for now, to build the CLI by yourself. You can do this by:
1. Installing the Go compiler (also known as the Golang compiler)
2. Run this script: https://github.com/CanastaWiki/Canasta-CLI/blob/main/build.sh

**Comment by ImMarkP** [comment]
That's got it - thank you very much! Looking forward to trying this out!
