### ISSUE TITLE
Use of AMD-specific yq binary causes extension loading to fail in ARM architecture

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#401]
I believe this AMD-specific line causes Canasta setup to fail on any computer that uses ARM architecture, which is most notably Apple computers (?):

https://github.com/CanastaWiki/Canasta/blob/master/Dockerfile#L141

Perhaps the best solution is to use a YAML parser that is not architecture-specific? I don't know much about YAML parsers, but I would have to imagine that there's some YAML-parsing library or script that will work across all machines... I mean, PHP even contains a yaml_parse() function, so I would think there are any number of ways to do it.

**Comment by jeffw16** [comment]
Oh that's why!!

**Comment by jeffw16** [comment]
Does that repo not have an aarch64 binary to download too?

**Comment by yaronkoren** [comment]
It does... but wouldn't it be better to use platform-neutral code? It just seems like such a trivial task to parse a YAML file...
