### ISSUE TITLE
Switch to using PHP-FPM and mpm_event

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#54]
Currently, we use mpm_prefork, which is thread-safe. This tends to be a bit slower since new processes are spun up just-in-time (hence the name prefork, as the forking happens after the request is made to the server). mpm_event enables multithreading and keeps processes on the backburner ahead of time. With the amount of resources that Canasta requires, it doesn't seem like it makes sense to keep using mpm_prefork. [Pages on MediaWiki.org](https://www.mediawiki.org/wiki/Manual:Performance_tuning#Web_server) written by WMF staff seem to recommend using mpm_event. The switch to mpm_event at MyWikis has been nothing but great for us. Using mpm_event will require us to switch to an implementation of PHP that supports multithreading, namely PHP-FPM.

**Comment by FelipoAntonoff** [comment]
Good idea, MediaWiki really recommends this change, I have been using PHP FPM with Phalcon and Opencart for many years and it has 100% met our usage and with low consumption.

I also recommend the Nginx server, I consider it the best web server, is there any reason why Apache is preferred in the project?

**Comment by jeffw16** [comment]
@FelipoAntonoff Hi, pleasure to meet you. We use Apache because this is what the Wikimedia Foundation uses to run Wikipedia and sister sites. We believe that sticking as close to the WMF's tech stack as possible best positions Canasta to take full advantage of MediaWiki's functionality and adapt faster to any future updates made to MediaWiki.

**Comment by FelipoAntonoff** [comment]
Hi @jeffw16 thanks for the info, it really makes sense in this case and maybe it's more common setting for many people.

**Comment by jeffw16** [comment]
By the way, I personally have no reservations against Nginx; in fact, I agree it is more performant and nimble. If one day WMF switches to using Nginx and MediaWiki's support for Nginx surpasses that of Apache, then I think Canasta, at that point, should switch to Nginx.

**Comment by FelipoAntonoff** [comment]
The sim really makes sense and a great idea if one day they switch to Nginx.

**Comment by PiyushRaj927** [comment]
I would like to work on this. Could you please assign this to me?

**Comment by jeffw16** [comment]
Assigned.

**Comment by PiyushRaj927** [comment]
Hi @jeffw16, nice to meet you. I'm new to Apache and need clarification on which directives to include in the `mpm_event.conf` config file for the mpm_event, like the [mpm_prefork.conf](https://github.com/CanastaWiki/Canasta/blob/master/_sources/configs/mpm_prefork.conf) for the prefork module and how to decide on the values, should I use the default values as per the Apache documentation.

**Comment by jeffw16** [comment]
@PiyushRaj927 go ahead and try using the default values. We can tweak it later. Hope that helps!

**Comment by jeffw16** [comment]
Done through #222
