### ISSUE TITLE
Add a blank (or stub) /config/composer.local.json file?

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#63]
I think it would be helpful to add a stub composer.local.json file to the /config directory (as a Docker volume), which would be either blank or (maybe better yet) look something like:

```
{
	"extra": {
		"merge-plugin": {
			"include": [
			]
		}
	}
}
```

This could make life easier for the administrator - so that they know where that file should go, and what it should look like.

**Comment by jeffw16** [comment]
I agree completely

**Comment by jeffw16** [comment]
This could probably be added in the Canasta-DockerCompose repo.

**Comment by yaronkoren** [comment]
What would be the benefit of that (if any)?

**Comment by jeffw16** [comment]
That's eventually going to be the correct place to make this change. Right now, the Docker Compose "stack" is intermingled with the stuff that comprises the Canasta image. We should split them in the near future.

**Comment by yaronkoren** [comment]
Looks like this is done now! This issue is halfway between "resolved" and "declined", since the file was added, though to the Docker Compose repository and not this one.
