### ISSUE TITLE
Begin Canasta development for MW 1.39 alpha

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#75]
MediaWiki 1.39 is being released in a few months. Wikimedia Foundation wikis are already running on `wmf` releases of 1.39. We should take a look at the changes made between MediaWiki 1.36 to 1.39 and see what needs to be done to adapt Canasta.

**Comment by FelipoAntonoff** [comment]
Good idea, looks like they plan to release in 11/2022 at 1.39 LTS.

Can you tell if Canasta mainly focuses on LTS versions of MediaWiki.

**Comment by jeffw16** [comment]
@FelipoAntonoff Yes, one of the seven guiding principles of Canasta is stability. At the moment, we only support LTS versions. If there is enough demand in the future (and enough developers to support it), we will consider adding support for non-LTS major releases too.

**Comment by FelipoAntonoff** [comment]
Good to know, really to avoid too many changes in a short time to improve maybe wait for the LTS, so it's also easier to deal with the Canasta code.

Thanks for the information.

**Comment by jeffw16** [comment]
See #141
