### ISSUE TITLE
Right way to use this project for CI

### ISSUE THREAD

**Issue by nischayn22** [CanastaWiki/Canasta#8]
What would be the right way to maintain a wiki instance for regular deployment using Canasta?

I have a use case where we have custom extensions, LocalSettings file, etc. We want to have all our configurations, etc on a separate git repo. However, the current architecture requires files to be within the config/ or extensions/ folder making it difficult.

**Comment by nischayn22** [comment]
Okay, this makes more sense. I think adding an example for the same would make sense?

**Comment by jeffw16** [comment]
@vedmaka How feasible would using compose-extend be? Are there any features that would be missing if we were to use compose-extend as opposed to a regular docker-compose.yml without any extending? (I wouldn't think so myself, but I wanted to double check.)

I think we should try to use compose-extend if possible. Then we can have a stack repo that sits beside the Canasta image. How does this sound?

**Comment by vedmaka** [comment]
@jeffw16 

> Are there any features that would be missing if we were to use compose-extend as opposed to a regular docker-compose.yml without any extending?

Yup, no drawbacks here

> Then we can have a stack repo that sits beside the Canasta image

Yup, sounds good

**Comment by amalpaul54111** [comment]
Do we have this particular solution "stack-repo" or whatever it is executed? If not, is this something I can work?
Was https://github.com/WikiWorks/Canasta-DockerCompose made for this purpose?

**Comment by jeffw16** [comment]
The stack repo has not yet been finalized. I created the WikiWorks/Canasta-DockerCompose repo but we haven't yet had the chance to initialize it. The goal is to move the following onto it:

- `docker-compose.yml`
- `kubernetes/`
- `config/`
- and maybe some more things I didn't yet have the chance to look at

**Comment by amalpaul54111** [comment]
So can I work on it. It would also be useful when we are building an CLI tool for Canasta. I believe this is not a tedious task. We just have to make sure there are all the files to get started to deploy a MediaWiki Site, right? Please correct me if I am wrong.

**Comment by jeffw16** [comment]
@amalpaul54111 That's correct! Feel free to make a PR on CanastaWiki/Canasta-DockerCompose to add all Docker Compose-related files onto it, but without anything Kubernetes-specific.

**Comment by yaronkoren** [comment]
Closing this - I believe support for Docker Compose has been available for a long time now. (And of course, this question was answered even before then.)
