### ISSUE TITLE
Extension assets are not loaded from canasta-extensions

### ISSUE THREAD

**Issue by nischayn22** [CanastaWiki/Canasta#90]
On using PageForms the following paths are used to load extension assets:

/w/extensions/PageForms/skins/loadingbg.png

instead of 

/w/canasta-extensions/PageForms/skins/loadingbg.png

**Comment by jeffw16** [comment]
@yaronkoren I think this is a question for you 😊

**Comment by yaronkoren** [comment]
This may have been fixed before, but in any case I believe this is no longer an issue, now that symlinks are used for every bundled extension (including Page Forms).
