### ISSUE TITLE
Remove MobileDetect extension

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#92]
The MobileDetect extension (https://www.mediawiki.org/wiki/Extension:MobileDetect) lacks an extension.json file, and thus can't be loaded via cfLoadExtension() or wfLoadExtension(). That's not just an oversight - it's done on purpose, because loading it via extension.json would disable some of its functionality:

https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/MobileDetect/+/refs/heads/master/MobileDetect.php#35

Given that, it seems obvious that this extension should be removed from Canasta. It doesn't seem like that useful an extension anyway; I've personally never heard of anyone using it. And no one has yet complained about its inability to be called within Canasta, which presumably means that no one has tried using it yet.

**Comment by jeffw16** [comment]
Sounds good to me. Was this meant to be a pull request?

**Comment by yaronkoren** [comment]
Cool. No - there's an attached pull request. I wasn't sure whether to just put this whole comment in the pull request, but I figured making a separate issue would be better.

**Comment by jeffw16** [comment]
OK, I don't see the pull request. Would you be able to mention it in here so GitHub knows to link this issue to the PR?

**Comment by yaronkoren** [comment]
It's here: 9e4a0f6b63935e4398ef4d5d2c321c20ac07aeef

**Comment by jeffw16** [comment]
Hmm, that's not a PR, just a commit made to a branch. Would you please be able to make one on the PRs page?

**Comment by yaronkoren** [comment]
Oops... I forgot to actually turn it into a pull request. I just did that now.

**Comment by jeffw16** [comment]
Closed by #93
