### ISSUE TITLE
Fix or remove the Favorites extension

### ISSUE THREAD

**Issue by yaronkoren** [CanastaWiki/Canasta#94]
Favorites is a MediaWiki extension contained in Canasta that lets you mark different wiki pages as your "favorites", and then view the list of your favorites:

https://www.mediawiki.org/wiki/Extension:Favorites

As you can see, last month two big warnings were added to the page: that the extension is incompatible with MW 1.33+, and that it's unmaintained.

The incompatibility is because it calls a method, APIBase::dieUsageMsg(), that was removed in MW 1.32.  And due to some very strange coding, this method seems to always get called - not just on errors. (?) See here:

https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/Favorites/+/refs/heads/master/includes/api/ApiFavorite.php#33

On top of that, Favorites also uses a hook, InternalParseBeforeSanitize, that was deprecated in MW 1.35:

https://www.mediawiki.org/wiki/Manual:Hooks/InternalParseBeforeSanitize

So, I see two options for this extension: improve it ourselves, or remove it from Canasta. (There's also the option of just waiting and hoping that someone else will fix it, but that seems optimistic.) Personally, I vote for removing it - I don't really see the point of marking certain pages as your favorites, and for users who really want to do that, they could always use browser bookmarks or something along those lines.

**Comment by tosfos** [comment]
I say remove

**Comment by jeffw16** [comment]
I support removing as well
