### ISSUE TITLE
Missing comments for loading extensions and skins

### ISSUE THREAD

**Issue by sanjay-thiyagarajan** [CanastaWiki/Canasta#97]
Steps to reproduce:
1) Clone this repo and run Canasta using Docker compose.
2) Complete MediaWiki installation (web)
3) Bring down the containers using ```docker-compose down``` and start again using ```docker-compose up -d```
3) Check the generated LocalSettings.php (It is supposed to contain all the load calls for extensions and skins initially)

**Comment by jeffw16** [comment]
We don't do this anymore because of the rearchitecture that we did to launch Canasta 1.0. https://github.com/CanastaWiki/Canasta/commit/dc9e02589141b675e7317e2d1dd5eac227044897
